/**
 * Generated by Scrooge
 *   version: 4.6.0
 *   rev: eb57ae5452b3a7a1fe18ba3ebf6bcc0721393d8c
 *   built at: 20160419-093119
 */
package snapple.finagle.io

import com.twitter.finagle.Thrift
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.scrooge.{ThriftStruct, TReusableMemoryTransport}
import com.twitter.util.{Future, Return, Throw, Throwables}
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryInputTransport
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, HashMap => mutable$HashMap}
import scala.collection.{Map, Set}

import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class SnappleService$FinagleService(
  iface: SnappleService[Future],
  protocolFactory: TProtocolFactory,
  stats: StatsReceiver,
  maxThriftBufferSize: Int,
  serviceName: String
) extends com.twitter.finagle.Service[Array[Byte], Array[Byte]] {
  import SnappleService._

  def this(
    iface: SnappleService[Future],
    protocolFactory: TProtocolFactory,
    stats: StatsReceiver,
    maxThriftBufferSize: Int
  ) = this(iface, protocolFactory, stats, maxThriftBufferSize, "SnappleService")

  def this(
    iface: SnappleService[Future],
    protocolFactory: TProtocolFactory
  ) = this(iface, protocolFactory, NullStatsReceiver, Thrift.maxThriftBufferSize)

  private[this] val tlReusableBuffer = new ThreadLocal[TReusableMemoryTransport] {
    override def initialValue() = TReusableMemoryTransport(512)
  }

  private[this] def reusableBuffer: TReusableMemoryTransport = {
    val buf = tlReusableBuffer.get()
    buf.reset()
    buf
  }

  private[this] val resetCounter = stats.scope("buffer").counter("resetCount")

  private[this] def resetBuffer(trans: TReusableMemoryTransport): Unit = {
    if (trans.currentCapacity > maxThriftBufferSize) {
      resetCounter.incr()
      tlReusableBuffer.remove()
    }
  }

  protected val functionMap = new mutable$HashMap[String, (TProtocol, Int) => Future[Array[Byte]]]()

  protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
    functionMap(name) = f
  }

  protected def exception(name: String, seqid: Int, code: Int, message: String): Future[Array[Byte]] = {
    try {
      val x = new TApplicationException(code, message)
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport().flush()
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  protected def reply(name: String, seqid: Int, result: ThriftStruct): Future[Array[Byte]] = {
    try {
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()

        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  final def apply(request: Array[Byte]): Future[Array[Byte]] = {
    val inputTransport = new TMemoryInputTransport(request)
    val iprot = protocolFactory.getProtocol(inputTransport)

    try {
      val msg = iprot.readMessageBegin()
      val func = functionMap.get(msg.name)
      func match {
        case _root_.scala.Some(fn) =>
          fn(iprot, msg.seqid)
        case _ =>
          TProtocolUtil.skip(iprot, TType.STRUCT)
          exception(msg.name, msg.seqid, TApplicationException.UNKNOWN_METHOD,
            "Invalid method name: '" + msg.name + "'")
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  // ---- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_ping {
    val RequestsCounter = scopedStats.scope("ping").counter("requests")
    val SuccessCounter = scopedStats.scope("ping").counter("success")
    val FailuresCounter = scopedStats.scope("ping").counter("failures")
    val FailuresScope = scopedStats.scope("ping").scope("failures")
  }
  addFunction("ping", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_ping.RequestsCounter.incr()
      val args = Ping.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.ping()
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Unit =>
        reply("ping", seqid, Ping.Result())
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_ping.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_ping.FailuresCounter.incr()
          __stats_ping.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("ping", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_propagate {
    val RequestsCounter = scopedStats.scope("propagate").counter("requests")
    val SuccessCounter = scopedStats.scope("propagate").counter("success")
    val FailuresCounter = scopedStats.scope("propagate").counter("failures")
    val FailuresScope = scopedStats.scope("propagate").scope("failures")
  }
  addFunction("propagate", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_propagate.RequestsCounter.incr()
      val args = Propagate.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.propagate(args.values)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Unit =>
        reply("propagate", seqid, Propagate.Result())
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_propagate.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_propagate.FailuresCounter.incr()
          __stats_propagate.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("propagate", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_createEntry {
    val RequestsCounter = scopedStats.scope("createEntry").counter("requests")
    val SuccessCounter = scopedStats.scope("createEntry").counter("success")
    val FailuresCounter = scopedStats.scope("createEntry").counter("failures")
    val FailuresScope = scopedStats.scope("createEntry").scope("failures")
  }
  addFunction("createEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_createEntry.RequestsCounter.incr()
      val args = CreateEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.createEntry(args.key, args.dataKind, args.elementKind)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Boolean =>
        reply("createEntry", seqid, CreateEntry.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_createEntry.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_createEntry.FailuresCounter.incr()
          __stats_createEntry.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("createEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_removeEntry {
    val RequestsCounter = scopedStats.scope("removeEntry").counter("requests")
    val SuccessCounter = scopedStats.scope("removeEntry").counter("success")
    val FailuresCounter = scopedStats.scope("removeEntry").counter("failures")
    val FailuresScope = scopedStats.scope("removeEntry").scope("failures")
  }
  addFunction("removeEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_removeEntry.RequestsCounter.incr()
      val args = RemoveEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.removeEntry(args.key)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Boolean =>
        reply("removeEntry", seqid, RemoveEntry.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_removeEntry.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_removeEntry.FailuresCounter.incr()
          __stats_removeEntry.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("removeEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_getEntry {
    val RequestsCounter = scopedStats.scope("getEntry").counter("requests")
    val SuccessCounter = scopedStats.scope("getEntry").counter("success")
    val FailuresCounter = scopedStats.scope("getEntry").counter("failures")
    val FailuresScope = scopedStats.scope("getEntry").scope("failures")
  }
  addFunction("getEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_getEntry.RequestsCounter.incr()
      val args = GetEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getEntry(args.key)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: snapple.finagle.io.TOptionalDataType =>
        reply("getEntry", seqid, GetEntry.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_getEntry.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_getEntry.FailuresCounter.incr()
          __stats_getEntry.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_modifyEntry {
    val RequestsCounter = scopedStats.scope("modifyEntry").counter("requests")
    val SuccessCounter = scopedStats.scope("modifyEntry").counter("success")
    val FailuresCounter = scopedStats.scope("modifyEntry").counter("failures")
    val FailuresScope = scopedStats.scope("modifyEntry").scope("failures")
  }
  addFunction("modifyEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_modifyEntry.RequestsCounter.incr()
      val args = ModifyEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.modifyEntry(args.key, args.operation, args.element)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Boolean =>
        reply("modifyEntry", seqid, ModifyEntry.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_modifyEntry.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_modifyEntry.FailuresCounter.incr()
          __stats_modifyEntry.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("modifyEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_getAllEntries {
    val RequestsCounter = scopedStats.scope("getAllEntries").counter("requests")
    val SuccessCounter = scopedStats.scope("getAllEntries").counter("success")
    val FailuresCounter = scopedStats.scope("getAllEntries").counter("failures")
    val FailuresScope = scopedStats.scope("getAllEntries").scope("failures")
  }
  addFunction("getAllEntries", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_getAllEntries.RequestsCounter.incr()
      val args = GetAllEntries.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getAllEntries()
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Map[String, snapple.finagle.io.TDataType] =>
        reply("getAllEntries", seqid, GetAllEntries.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_getAllEntries.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_getAllEntries.FailuresCounter.incr()
          __stats_getAllEntries.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getAllEntries", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
}