/**
 * Generated by Scrooge
 *   version: 4.6.0
 *   rev: eb57ae5452b3a7a1fe18ba3ebf6bcc0721393d8c
 *   built at: 20160416-204730
 */
package snapple.finagle.io

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object TOptionalDataType extends ThriftStructCodec3[TOptionalDataType] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("TOptionalDataType")
  val DataTypeField = new TField("dataType", TType.STRUCT, 1)
  val DataTypeFieldManifest = implicitly[Manifest[snapple.finagle.io.TDataType]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      DataTypeField,
      true,
      false,
      DataTypeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: TOptionalDataType): Unit = {
  }

  def withoutPassthroughFields(original: TOptionalDataType): TOptionalDataType =
    new Immutable(
      dataType =
        {
          val field = original.dataType
          field.map { field =>
            snapple.finagle.io.TDataType.withoutPassthroughFields(field)
          }
        }
    )

  override def encode(_item: TOptionalDataType, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): TOptionalDataType = {

    var dataType: Option[snapple.finagle.io.TDataType] = None

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRUCT =>

                dataType = Some(readDataTypeValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'dataType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      dataType,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): TOptionalDataType =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): TOptionalDataType = {
    var dataType: _root_.scala.Option[snapple.finagle.io.TDataType] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRUCT =>
                dataType = _root_.scala.Some(readDataTypeValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'dataType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      dataType,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    dataType: _root_.scala.Option[snapple.finagle.io.TDataType] = _root_.scala.None
  ): TOptionalDataType =
    new Immutable(
      dataType
    )

  def unapply(_item: TOptionalDataType): _root_.scala.Option[_root_.scala.Option[snapple.finagle.io.TDataType]] = _root_.scala.Some(_item.dataType)


  @inline private def readDataTypeValue(_iprot: TProtocol): snapple.finagle.io.TDataType = {
    snapple.finagle.io.TDataType.decode(_iprot)
  }

  @inline private def writeDataTypeField(dataType_item: snapple.finagle.io.TDataType, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DataTypeField)
    writeDataTypeValue(dataType_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeDataTypeValue(dataType_item: snapple.finagle.io.TDataType, _oprot: TProtocol): Unit = {
    dataType_item.write(_oprot)
  }


  object Immutable extends ThriftStructCodec3[TOptionalDataType] {
    override def encode(_item: TOptionalDataType, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): TOptionalDataType = TOptionalDataType.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[TOptionalDataType] = TOptionalDataType.metaData
  }

  /**
   * The default read-only implementation of TOptionalDataType.  You typically should not need to
   * directly reference this class; instead, use the TOptionalDataType.apply method to construct
   * new instances.
   */
  class Immutable(
      val dataType: _root_.scala.Option[snapple.finagle.io.TDataType],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends TOptionalDataType {
    def this(
      dataType: _root_.scala.Option[snapple.finagle.io.TDataType] = _root_.scala.None
    ) = this(
      dataType,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val dataType: _root_.scala.Option[snapple.finagle.io.TDataType],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends TOptionalDataType {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the TOptionalDataType trait with additional state or
   * behavior and implement the read-only methods from TOptionalDataType using an underlying
   * instance.
   */
  trait Proxy extends TOptionalDataType {
    protected def _underlying_TOptionalDataType: TOptionalDataType
    override def dataType: _root_.scala.Option[snapple.finagle.io.TDataType] = _underlying_TOptionalDataType.dataType
    override def _passthroughFields = _underlying_TOptionalDataType._passthroughFields
  }
}

trait TOptionalDataType
  extends ThriftStruct
  with scala.Product1[Option[snapple.finagle.io.TDataType]]
  with java.io.Serializable
{
  import TOptionalDataType._

  def dataType: _root_.scala.Option[snapple.finagle.io.TDataType]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = dataType


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (dataType.isDefined) {
                writeDataTypeValue(dataType.get, _oprot)
                _root_.scala.Some(TOptionalDataType.DataTypeField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): TOptionalDataType = {
    var dataType: _root_.scala.Option[snapple.finagle.io.TDataType] = this.dataType
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        dataType = _root_.scala.Some(readDataTypeValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      dataType,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): TOptionalDataType = {
    var dataType: _root_.scala.Option[snapple.finagle.io.TDataType] = this.dataType

    _fieldId match {
      case 1 =>
        dataType = _root_.scala.None
      case _ =>
    }
    new Immutable(
      dataType,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetDataType: TOptionalDataType = unsetField(1)


  override def write(_oprot: TProtocol): Unit = {
    TOptionalDataType.validate(this)
    _oprot.writeStructBegin(Struct)
    if (dataType.isDefined) writeDataTypeField(dataType.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    dataType: _root_.scala.Option[snapple.finagle.io.TDataType] = this.dataType,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): TOptionalDataType =
    new Immutable(
      dataType,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[TOptionalDataType]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[TOptionalDataType]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 1

  override def productElement(n: Int): Any = n match {
    case 0 => this.dataType
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "TOptionalDataType"
}
