/**
 * Generated by Scrooge
 *   version: 4.6.0
 *   rev: eb57ae5452b3a7a1fe18ba3ebf6bcc0721393d8c
 *   built at: 20160416-204730
 */
package snapple.finagle.io

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object TVersionVector extends ThriftStructCodec3[TVersionVector] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("TVersionVector")
  val VersionsField = new TField("versions", TType.MAP, 1)
  val VersionsFieldManifest = implicitly[Manifest[Map[String, Long]]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      VersionsField,
      false,
      false,
      VersionsFieldManifest,
      _root_.scala.Some(implicitly[Manifest[String]]),
      _root_.scala.Some(implicitly[Manifest[Long]]),
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: TVersionVector): Unit = {
  }

  def withoutPassthroughFields(original: TVersionVector): TVersionVector =
    new Immutable(
      versions =
        {
          val field = original.versions
          field.map { case (key, value) =>
              val newKey = {
              val field = key
              field
            }
  
          
              val newValue = {
              val field = value
              field
            }
  
          
            newKey -> newValue
          }
        }
    )

  override def encode(_item: TVersionVector, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): TVersionVector = {

    var versions: Map[String, Long] = Map[String, Long]()

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.MAP =>
    
                versions = readVersionsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.MAP
                throw new TProtocolException(
                  "Received wrong type for field 'versions' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      versions,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): TVersionVector =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): TVersionVector = {
    var versions: Map[String, Long] = Map[String, Long]()
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.MAP =>
                versions = readVersionsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.MAP
                throw new TProtocolException(
                  "Received wrong type for field 'versions' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      versions,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    versions: Map[String, Long] = Map[String, Long]()
  ): TVersionVector =
    new Immutable(
      versions
    )

  def unapply(_item: TVersionVector): _root_.scala.Option[Map[String, Long]] = _root_.scala.Some(_item.versions)


  @inline private def readVersionsValue(_iprot: TProtocol): Map[String, Long] = {
    val _map = _iprot.readMapBegin()
    if (_map.size == 0) {
      _iprot.readMapEnd()
      Map.empty[String, Long]
    } else {
      val _rv = new mutable$HashMap[String, Long]
      var _i = 0
      while (_i < _map.size) {
        val _key = {
          _iprot.readString()
        }
        val _value = {
          _iprot.readI64()
        }
        _rv(_key) = _value
        _i += 1
      }
      _iprot.readMapEnd()
      _rv
    }
  }

  @inline private def writeVersionsField(versions_item: Map[String, Long], _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(VersionsField)
    writeVersionsValue(versions_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeVersionsValue(versions_item: Map[String, Long], _oprot: TProtocol): Unit = {
    _oprot.writeMapBegin(new TMap(TType.STRING, TType.I64, versions_item.size))
    versions_item.foreach { case (versions_item_key, versions_item_value) =>
      _oprot.writeString(versions_item_key)
      _oprot.writeI64(versions_item_value)
    }
    _oprot.writeMapEnd()
  }


  object Immutable extends ThriftStructCodec3[TVersionVector] {
    override def encode(_item: TVersionVector, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): TVersionVector = TVersionVector.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[TVersionVector] = TVersionVector.metaData
  }

  /**
   * The default read-only implementation of TVersionVector.  You typically should not need to
   * directly reference this class; instead, use the TVersionVector.apply method to construct
   * new instances.
   */
  class Immutable(
      val versions: Map[String, Long],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends TVersionVector {
    def this(
      versions: Map[String, Long] = Map[String, Long]()
    ) = this(
      versions,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val versions: Map[String, Long],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends TVersionVector {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the TVersionVector trait with additional state or
   * behavior and implement the read-only methods from TVersionVector using an underlying
   * instance.
   */
  trait Proxy extends TVersionVector {
    protected def _underlying_TVersionVector: TVersionVector
    override def versions: Map[String, Long] = _underlying_TVersionVector.versions
    override def _passthroughFields = _underlying_TVersionVector._passthroughFields
  }
}

trait TVersionVector
  extends ThriftStruct
  with scala.Product1[Map[String, Long]]
  with java.io.Serializable
{
  import TVersionVector._

  def versions: Map[String, Long]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = versions


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (versions ne null) {
                writeVersionsValue(versions, _oprot)
                _root_.scala.Some(TVersionVector.VersionsField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): TVersionVector = {
    var versions: Map[String, Long] = this.versions
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        versions = readVersionsValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      versions,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): TVersionVector = {
    var versions: Map[String, Long] = this.versions

    _fieldId match {
      case 1 =>
        versions = Map[String, Long]()
      case _ =>
    }
    new Immutable(
      versions,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetVersions: TVersionVector = unsetField(1)


  override def write(_oprot: TProtocol): Unit = {
    TVersionVector.validate(this)
    _oprot.writeStructBegin(Struct)
    if (versions ne null) writeVersionsField(versions, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    versions: Map[String, Long] = this.versions,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): TVersionVector =
    new Immutable(
      versions,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[TVersionVector]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[TVersionVector]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 1

  override def productElement(n: Int): Any = n match {
    case 0 => this.versions
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "TVersionVector"
}